apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-caddyfile
  namespace: kube-system
data:
  Caddyfile: |
    {
      admin off
    }
    
    :80, :443 {
      reverse_proxy /* kavita.kavita.svc.cluster.local:5000
    }
    
    fedora.tailf20727.ts.net {
      tls internal
      reverse_proxy /* kavita.kavita.svc.cluster.local:5000
    }
    
    *.tailf20727.ts.net {
      tls internal
      reverse_proxy /* kavita.kavita.svc.cluster.local:5000
    }