apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - caddy        # Ingress controller (must apply first)
  - kavita
  - minio
  - psql
  - n8n
  - qbittorrent
  - paperless
  - redis
