---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBXqiYv5ZdVuf8vPNhwZSgwTfJRpV829tkcfV6Wci5SjpUhS2MDRstfJtGHimtjdgeN1D96pdu+ISP3KzjC7BjUgLAddik1YMgcK3/brifHP4KuX2Q8EVTCwRoPegeFQeKInE+z8jQpTv+7WpxdAV+4hqFLYqOdV7XTLfJQCl6A1TdtsUocTBmk7DiLyzy5olX4wV3qliqNmQnHxy+G43mDtyeYxNQ57LTv+A2QPcVv3uQrRZdPCykEgKE75XNzLGxi0g/VjLIuu5y4l3uytUjDanBujuk6oXMk8XI47SY3Y/kQEql17p7qaHWNovNTdSQ7nbwF3+7pqWnjVZL7BS+89MyvMUwY0EAChdUgZHV7oLZog5UHWYDgJ5+6WE3jeLp7okTq+3KZRNLUCFpdeBUW0FxdqJHlPKHsJMrsFS+Nw9UON2wbeEZPcEkNcffWCiXUFq3X+8MCsF/KbjhyrANf67XVtigHzGMfKo4BljmdQyD1Gor5ro5obfrkgqH7oLZ6Z0WT48CvtoMQ/S4iGi1mADZglmgGINO/F8aXGhX1IVmCD42wbY8niXU8zMzRR5bR9dzvZcYdEnMPQjTKEvVbvAnq9b9ijxavMMjSamf5Ub9i7ZHD9NHWPK3hh6kY6ziJGFJS2Q/ocfmbmai/NBuQvLCGor6zkNxtGsM5KleCmR54gA3Yt0MhkSjFymVyPJdA0hwGjY3gya4=
  template:
    metadata:
      name: postgres-auth
      namespace: postgres
    type: Opaque
