apiVersion: v1
kind: Service
metadata:
  name: paperless-nodeport
  namespace: paperless
spec:
  type: NodePort
  selector:
    app: paperless
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30008