apiVersion: v1
kind: Service
metadata:
  name: kavita-nodeport
  namespace: kavita
spec:
  type: NodePort
  selector:
    app: kavita
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30001

