apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - postgres-services.yaml
  - postgres-statefulset.yaml
